name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ ubuntu-16.04, macos-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: make -j
